In [174]:
import numpy as np
import math

In [175]:
def sigmoid(z):
    return 1./(1+np.exp(-z))

In [176]:
def log_loss(t, y):
    return np.sum((-t*np.log(y) - (1 - t) * (np.log(1 - y))), keepdims=True).flatten()

def diff_log_loss(t, y):
    return np.sum(-t/y +(1-t)/(1-y), keepdims=True)

In [177]:
def logos(sample):
    sigmoid(sample.dot(w) + b)

In [178]:
class Layer: #слой реализован в виде класса
  
    
    def __init__(self, n_inp, n_out, lr=0.1):
        self.shape = (n_inp, n_out) #залетают входящие и выходящие значения
        self.lr = lr #шаг обучения
        self.w = np.zeros(self.shape, dtype=np.float32) #веса в начале заданы нулями
        self.b = np.zeros((1, n_out), dtype=np.float32) #смещения в начале заданы нулями
        self._clear_grads() #проход обычного градиентного спуска

    def _clear_grads(self): #градиентный спуск
        self.inp = None
        self.activations = None
        self.d_sigma = None
        self.d_w = None
        self.d_b = None

    def __call__(self, x): #вызов класса
        if len(x.shape) == 1: #если входящие значения одноразмерны - сменить размерность
            x = x.reshape(1, -1)
        self.inp = x #задаем входные значения
        self.activations = sigmoid(x.astype(np.float64).dot(self.w) + self.b) #запуск функции с функцией активации
        return self.activations

    def backward(self, grad): # обратный проход
        self.d_sigma = self.activations * (1 - self.activations) #производная функции ошибки 
        self.d_w = self.grad_w(grad)
        self.d_b = self.grad_b(grad)
        return self.grad_x(grad)

    def grad_w(self, grad):
        return grad * self.inp.T * self.d_sigma

    def grad_b(self, grad):
        return grad * self.d_sigma

    def grad_x(self, grad):
        return self.w.dot(grad) * self.d_sigma

    def step(self):
        self.w -= self.d_w * self.lr
        self.b -= self.d_b * self.lr
        self._clear_grads()
        #return(self.w, self.b)
    
    def logos(self,sample):
        return(sigmoid(sample.dot(self.w) + self.b))

In [179]:
l1 = Layer(5, 1)

In [180]:
l1.w

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [181]:
mu_0 = np.random.normal(1.0, 1.0, (2,10))
mu_1 = np.random.normal(-1.0, 1.0, (2,10))

In [182]:
x = np.array([1., 2., 1., -1., -2.])

In [183]:
x.shape

(5,)

In [184]:
mu_0

array([[ 2.00855142, -0.25853459,  0.34003996,  0.91061157,  2.36640556,
         0.03322055,  2.62449064,  1.50196047,  2.47277812,  0.41639528],
       [ 2.94331361,  0.59850433,  0.81601085,  0.24064517,  0.57691763,
         0.58442088, -0.84375738,  3.14598512,  2.47442536,  1.7977619 ]])

In [185]:
mu_1 

array([[-2.82586377, -1.6520818 , -2.02787646, -1.40372847,  0.35820279,
        -0.711704  , -0.5556465 ,  0.46069878, -0.27493208, -1.66630366],
       [-1.75229028, -0.00548095, -0.91489477, -0.95036192, -1.30579134,
         0.34475563, -1.12828129, -0.40572341, -0.43681424, -1.0786922 ]])

In [186]:
t = mu_1
t.shape

(2, 10)

In [187]:
y = l1(x)

In [188]:
y

array([[0.5]])

In [189]:
log_loss(t[0], y)

array([6.93147181])

In [190]:
d_y = diff_log_loss(t[0], y)

In [191]:
d_y

array([[61.19694071]])

In [192]:
for line in t:
    #print(line.reshape(1,).shape)
    q = 0
    for i in range(10):
        y = l1(x)
        d_y = diff_log_loss(line, y)
        #print(d_y)
        l1.backward(d_y)
        l1.step()
    print(d_y)

[[8.43148366e+51]]
[[9.28255484e+92]]


In [193]:
y

array([[8.22357089e-93]])

In [194]:
t2 = mu_0

In [195]:
for line in t2:
    #print(line.reshape(1,).shape)
    q = 0
    for i in range(10):
        y = l1(x)
        d_y = diff_log_loss(line, y)
        #print(d_y)
        l1.backward(d_y)
        l1.step()
    print(d_y)

[[-8.35238246e+38]]
[[-5817092.90180548]]


In [196]:
y

array([[0.9999996]])

In [197]:
z = np.array([0.0609173])

In [203]:
log_loss(z, y)

array([3.92595227])

In [199]:
z = np.array([-0.06180425])

In [206]:
log_loss(z, y)

array([49.4003165])

In [204]:
z = np.random.normal(-1.0, 1.0, (2,1))

In [205]:
z

array([[-1.14406546],
       [-0.20996838]])