In [138]:
import numpy as np
import math

In [139]:
def sigmoid(z):
    return 1./(1+np.exp(-z))

In [140]:
def log_loss(t, y):
    return np.sum((-t*np.log(y) - (1 - t) * (np.log(1 - y))), keepdims=True).flatten()

def diff_log_loss(t, y):
    return np.sum(-t/y +(1-t)/(1-y), keepdims=True)

In [141]:
def logos(sample):
    sigmoid(sample.dot(w) + b)

In [142]:
class Layer: #слой реализован в виде класса
  
    
    def __init__(self, n_inp, n_out, lr=0.1):
        self.shape = (n_inp, n_out) #залетают входящие и выходящие значения
        self.lr = lr #шаг обучения
        self.w = np.zeros(self.shape, dtype=np.float32) #веса в начале заданы нулями
        self.b = np.zeros((1, n_out), dtype=np.float32) #смещения в начале заданы нулями
        self._clear_grads() #проход обычного градиентного спуска

    def _clear_grads(self): #градиентный спуск
        self.inp = None
        self.activations = None
        self.d_sigma = None
        self.d_w = None
        self.d_b = None

    def __call__(self, x): #вызов класса
        if len(x.shape) == 1: #если входящие значения одноразмерны - сменить размерность
            x = x.reshape(1, -1)
        self.inp = x #задаем входные значения
        self.activations = sigmoid(x.astype(np.float64).dot(self.w) + self.b) #запуск функции с функцией активации
        return self.activations

    def backward(self, grad): # обратный проход
        self.d_sigma = self.activations * (1 - self.activations) #производная функции ошибки 
        self.d_w = self.grad_w(grad)
        self.d_b = self.grad_b(grad)
        return self.grad_x(grad)

    def grad_w(self, grad):
        return grad * self.inp.T * self.d_sigma

    def grad_b(self, grad):
        return grad * self.d_sigma

    def grad_x(self, grad):
        return self.w.dot(grad) * self.d_sigma

    def step(self):
        self.w -= self.d_w * self.lr
        self.b -= self.d_b * self.lr
        self._clear_grads()
        #return(self.w, self.b)
    
    def logos(self,sample):
        return(sigmoid(sample.dot(self.w) + self.b))

In [143]:
l1 = Layer(5, 1)

In [144]:
l1.w

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [145]:
mu_0 = np.random.normal(1.0, 1.0, (1,10))
mu_1 = np.random.normal(-1.0, 1.0, (1,10))

In [146]:
x = np.array([1., 2., 1., -1., -2.])

In [147]:
x.shape

(5,)

In [148]:
mu_0

array([[-0.06891452,  1.39499817,  1.12433548,  1.63877758,  0.11285278,
         0.97803462,  1.51990391,  2.05639557,  1.32904124,  1.60439218]])

In [149]:
mu_1 

array([[-1.87913222, -2.24072271, -1.30568081, -1.36496615, -1.97694744,
        -1.34280162, -1.82289597,  0.82427666, -1.31056246,  0.04286237]])

In [150]:
t = mu_1
t.shape

(1, 10)

In [151]:
y = l1(x)

In [152]:
y

array([[0.5]])

In [153]:
log_loss(t[0], y)

array([6.93147181])

In [154]:
d_y = diff_log_loss(t[0], y)

In [155]:
d_y

array([[69.50628147]])

In [156]:
for line in t:
    #print(line.reshape(1,).shape)
    q = 0
    for i in range(10):
        y = l1(x)
        d_y = diff_log_loss(line, y)
        #print(d_y)
        l1.backward(d_y)
        l1.step()
    print(d_y)

[[5.61286305e+61]]


In [157]:
y

array([[2.20503694e-61]])

In [158]:
t2 = mu_0

In [159]:
for line in t2:
    #print(line.reshape(1,).shape)
    q = 0
    for i in range(10):
        y = l1(x)
        d_y = diff_log_loss(line, y)
        #print(d_y)
        l1.backward(d_y)
        l1.step()
    print(d_y)

[[-2.21205974e+13]]


In [160]:
y

array([[5.28458467e-13]])

In [161]:
z = np.array([0.0609173])

In [162]:
log_loss(z, y)

array([1.72205971])

In [165]:
z = np.array([-0.06180425])

In [166]:
log_loss(z, y)

array([-1.74713274])